---
title: "Leveraging Text Data in Healthcare: A Systematic Review of AI-Driven Emotional Analysis and Patient-Centric Innovations"
date: 2024-12-01
author:
  - name: Prashant Kumar Nag
    orcid: 0000-0002-1601-1455
    affiliation: Maulana Azad National Institute of Technology, Bhopal
  - name: Amit Bhagat
    affiliation: Maulana Azad National Institute of Technology, Bhopal
  - name: R. Vishnu Priya
    affiliation: National Institute of Technology Tiruchirappalli, Tamilnadu
  - name: Sunil Malviya
    affiliation: Maulana Azad National Institute of Technology, Bhopal
  - name: Sanjay Mishra
    affiliation: Maulana Azad National Institute of Technology, Bhopal
categories: 
  - AI in healthcare
  - Systematic Review
  - Emotional Analysis
  - Patient-Centric Care
  - Deep Learning
status: In Press
pub-info:
  reference: >-
    <strong>Prashant Kumar Nag</strong>, Amit Bhagat, R. Vishnu Priya, Sunil Malviya, and Sanjay Mishra, "Leveraging Text Data in Healthcare: A Systematic Review of AI-Driven Emotional Analysis and Patient-Centric Innovations," <em>International Conference,</em> 2024 (In Press)
  links: []
---

## Abstract

This systematic literature review (SLR) investigates how AI, deep learning (DL), and emotional analysis have been implemented/used in healthcare, and how they have influenced patient care and outcomes. AI techniques include methods of AI in diagnosis that have displayed undeniable promise in the areas of correct diagnosis, treatment plans that are individualized, and patient-therapist interaction. The review includes studies from 2014 to 2024, that explore the various sub-fields, including general healthcare, mental health, chronic disorders, and emergency care. It approves the main fields of deep learning techniques for sentiment analysis and emotion detection in healthcare and the high accuracy of the applications and other issues such as data quality, privacy concerns, model explainability, and assimilation into current healthcare systems. The study of emotional recognition is one such example of research that shows it is the application of AI models in emotional assessments done in real-time and detecting mental health conditions. Nevertheless, ethical and privacy issues are what make it difficult, thus, it is determined that proper consideration for data security and the public's confidence in artificial intelligence are required to solve the issues. The study concludes that further research should be conducted in the fields of data quality improvement and AI model explainability development and that AI systems should be interoperable within healthcare infrastructures. Nevertheless, even though there are barriers, AI and emotional analysis gives healthcare the capability of new patient outcome improvements and even more personalized care.

## Important links

- Paper (In Press)

## Citation

```bibtex
@inproceedings{nag2024LeveragingTextData,
  title = {Leveraging {Text} {Data} in {Healthcare}: {A} {Systematic} {Review} of {AI}-{Driven} {Emotional} {Analysis} and {Patient}-{Centric} {Innovations}},
  author = {Nag, Prashant Kumar and Bhagat, Amit and Priya, R Vishnu and Malviya, Sunil and Mishra, Sanjay},
  year = {2024},
  note = {In Press}
}
```
