---
title: "Enhancing Small Object Detection through Structure-Aware and Global Contextual Information"
date: 2024-08-01
author:
  - name: Deepak Kumar Khare
    affiliation: Maulana Azad National Institute of Technology, Bhopal
  - name: Amit Bhagat
    affiliation: Maulana Azad National Institute of Technology, Bhopal
  - name: R. Vishnu Priya
    affiliation: National Institute of Technology Tiruchirappalli, Tamilnadu
  - name: Prashant Kumar Nag
    orcid: 0000-0002-1601-1455
    affiliation: Maulana Azad National Institute of Technology, Bhopal
  - name: Sunil Malviya
    affiliation: Maulana Azad National Institute of Technology, Bhopal
categories: 
  - Object Detection
  - Small Object Detection
  - Deep Learning
  - Computer Vision
status: Published
pub-info:
  reference: >-
    Deepak Kumar Khare, Amit Bhagat, R. Vishnu Priya, <strong>Prashant Kumar Nag</strong>, and Sunil Malviya, "Enhancing Small Object Detection through Structure-Aware and Global Contextual Information," <em>Computer Research and Development,</em> vol. 24, no. 1000, pp. 85-99, August 2024, doi: <a href="https://doi.org/20.2040/crd.v24.2024.4259"><code>20.2040/crd.v24.2024.4259</code></a>
  links:
  - name: Published version
    url: http://journalcrd.org/wp-content/uploads/9-CRD2314.pdf
    icon: fa-solid fa-scroll
  - name: Add to Zotero
    url: https://www.zotero.org/save?type=doi&q=20.2040/crd.v24.2024.4259
    icon: ai ai-zotero
doi: 20.2040/crd.v24.2024.4259
---

## Abstract

In the task of small object detection, limitations such as fewer pixels, lack of rich features, and difficulty in feature extraction often lead to issues like missed detections, false detections, and low accuracy in models. To address these issues, a small object detection algorithm based on multi-scale structure-aware and global context information is proposed. A multi-scale structure-aware module is designed for complex scenarios to better capture the detailed features of small objects, thereby enhancing the model's ability to detect objects of different sizes. To obtain more global features, a global context information module is designed using the advantages of Transformers in capturing long-range dependency features, effectively establishing connections between pixel points in different regions. To address the gradient explosion phenomenon during model training, a new weighted loss function, W-FIoU, is designed, significantly improving the convergence speed during training. Extensive experimental results show that the proposed method achieves better detection results compared to other classic lightweight methods. Compared to the benchmark model, the proposed model improves mAP50 and mAP50:95 by 6.4 and 4.6 percentage points respectively on the VisDrone dataset, and also performs well on the TinyPerson dataset.

## Citation

<p class="buttons" style="text-align:center;">
<a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=20.2040/crd.v24.2024.4259">{{< ai zotero >}} Add to Zotero {{< fa square-arrow-up-right >}}</a>
</p>

```bibtex
@article{khare2024EnhancingSmallObject,
  title = {Enhancing {Small} {Object} {Detection} through {Structure}-{Aware} and {Global} {Contextual} {Information}},
  volume = {24},
  issn = {1000-1239},
  url = {http://journalcrd.org/wp-content/uploads/9-CRD2314.pdf},
  doi = {https://doi.org/20.2040/crd.v24.2024.4259},
  number = {1000},
  journal = {Computer Research and Development},
  author = {Khare, Deepak Kumar and Bhagat, Amit and Priya, R Vishnu and Nag, Prashant Kumar and Malviya, Sunil},
  month = aug,
  year = {2024},
  pages = {85--99}
}
```
