---
title: "Text-based emotion recognition using contextual phrase embedding model"
date: 2021-06-30
author:
  - name: Prashant Kumar Nag
    orcid: 0000-0002-1601-1455
    affiliation: Maulana Azad National Institue of Technology, Bhopal
  - name: R. Vishnu Priya
    affiliation: National Institute of Technology Tiruchirappalli, Tamilnadu
categories: 
  - Emotion recognition
  - Emotional cause
  - Skip phrase
  - FrameNet
  - Semantic role labelling
  - BERT 
status: Published
pub-info:
  reference: >-
    <strong>Prashant Kumar Nag</strong> and R. Vishnu Priya, “Text-based emotion recognition using contextual phrase embedding model” <em>Multimedia Tools and Applications,</em> Septermber 2023,82, 35329–35355 (2023) doi: <a href="https://doi.org/10.1145/3478586.3478629"><code>10.1145/3478586.3478629</code></a>
  links:
  - name: Published version
    url: https://doi.org/10.1007/s11042-023-14524-9
    icon: fa-solid fa-scroll
  - name: Add to Zotero
    url: https://www.zotero.org/save?type=doi&q=10.1007/s11042-023-14524-9
    icon: ai ai-zotero
doi: 10.1007/s11042-023-14524-9
haiku: 
  - When money is scarce;
  - when objectives are not shared—
  - don’t collaborate.
---

## Important links

-   Comming soon

## Abstract

In this paper, the proposed approach categories the sentences in the dataset into the various topical documents using the TE-LSTM+SC model. As well as, the model generates semantic words related to topics that are fed into the word embedding like Skip-Gram and FrameNet to build the domain-specific lexicon. The topically related sentences in each document are contextually grouped using Skip-Phrase. Each sentence in contextual group is given to Semantic Role Labelling (SRL). SRL indentify the essential predicate-argument structures with the semantic labels like verb (V) tag or ARGM-NEG or ARGM-PRP or ARGM-CAU or structures with the semantic labels like verb (V) tag or ARGM-NEG or ARGM-PRP or ARGM-CAU or ARGM-MNR or ARGM-MOD. The selected predicateargument structures are aggregated into a linear layer to form a semantic embedding. Simultaneously, the predicate-argument embedding is segmented to sub words by BERT. The sub-words are transformed to word level through a convolutional layer to acquire the contextual word representation. Finally, semantic embedding and word representation are integrated to efficiently find the emotion of the given sentence. The experimental result proved that the proposed approach outperforms all the state-of-art approaches.

## Important figure

<p class="buttons" style="text-align:center;">

<a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1007/s11042-023-14524-9">{{< ai zotero >}} Add to Zotero {{< fa square-arrow-up-right >}}</a>

</p>

``` bibtex
@article{2023r.TextbasedEmotionRecognition,
  title = {Text-Based Emotion Recognition Using Contextual Phrase Embedding Model},
  author = {R., Vishnu Priya and Nag, Prashant Kumar},
  date = {2023-03-16},
  journaltitle = {Multimedia Tools and Applications},
  shortjournal = {Multimed Tools Appl},
  issn = {1573-7721},
  doi = {10.1007/s11042-023-14524-9},
  url = {https://doi.org/10.1007/s11042-023-14524-9},
  urldate = {2023-03-30},
  langid = {english},
  keywords = {BERT,Emotion recognition,Emotional cause,FrameNet,MTAP,Semantic role labelling,Skip phrase},
  annotation = {0 citations (Crossref) [2023-10-05]}
}
```
