---
title: "Contextual BI-Directional Attention Flow With Embeddings From Language Models: A Generative Approach to Emotion Detection"
date: 2021-06-30
author:
  - name: Prashant Kumar Nag
    orcid: 0000-0002-1601-1455
    affiliation: Maulana Azad National Institue of Technology, Bhopal
  - name: Dr. R. Vishnu Priya
    affiliation: National Institute of Technology Tiruchirappalli, Tamilnadu
categories: 
  - Deep Learning
  - Word Embeddings
  - BiDAF
  - ELMo
  - RoBERT
  - Phrase Mining 
pub-info:
  reference: >-
    <strong>Prashant Kumar Nag</strong> and R. Vishnu Priya, “Contextual BI-Directional Attention Flow With Embeddings From Language Models: A Generative Approach to Emotion Detection” <em>Advances in Robotics - 5th International Conference of The Robotics Society(AIR2021)</em> Jun 30- July 4, 2021, Kanpur, India, ACM, New York, NY, USA, 6 pages, doi: <a href="https://doi.org/10.1145/3478586.3478629"><code>10.1145/3478586.3478629</code></a>
  links:
  - name: Published version
    url: https://doi.org/10.1145/3478586.3478629
    icon: fa-solid fa-scroll
  - name: Add to Zotero
    url: https://www.zotero.org/save?type=doi&q=10.1111/oik.07621
    icon: ai ai-zotero
doi: 10.1145/3478586.3478629
haiku: 
  - Fitness, turnover,
  - stability, evenness—
  - all due to constraints.
---

## Important links

-   Comming soon

## Abstract

Detection of Emotions from the text is a tedious task. Presently, existing models failed to detect the emotion in absence of the emotional word in the text. The cause phrase selection which gives a deep insight into emotions is considered to be a tough task. The proposed model for detecting emotions is developed through seven layers. Initially, the dataset is represented in the Topical documents using Adversarial Topic Modelling (ATM). Convolutional Neural Network (CNN) maps each phrase in the topical document to Higher-dimensional vectors, followed by the ELMo Model to obtain the fixed word Embeddings vectors. LSTM is responsible for making the interaction between the words in word embeddings and produces the context and query vectors. The bi-directional Attention flow layer determines the most relevant similarity between Context and Query. Finally, Robustly Optimized BERT (RoBERT) architecture is used to detect the Emotion. It is noted that the proposed multi-stage model detects better emotions than all the existing state-of-art models for detecting emotions.

## Important figure

<p class="buttons" style="text-align:center;">

<a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1145/3478586.3478629">{{< ai zotero >}} Add to Zotero {{< fa square-arrow-up-right >}}</a>

</p>

``` bibtex
@inproceedings{10.1145/3478586.3478629,
author = {Nag, Prashant Kumar and Priya R, Vishnu},
title = {Contextual BI-Directional Attention Flow With Embeddings From Language Models: A Generative Approach to Emotion Detection},
year = {2022},
isbn = {9781450389716},
publisher = {Association for Computing Machinery},
address = {New York, NY, USA},
url = {https://doi.org/10.1145/3478586.3478629},
doi = {10.1145/3478586.3478629},
booktitle = {Advances in Robotics - 5th International Conference of The Robotics Society},
articleno = {51},
numpages = {6},
keywords = {ELMo, RoBERT, Deep Learning, Word Embeddings, Phrase Mining, BiDAF},
location = {Kanpur, India},
series = {AIR2021}
}
```
