---
title: "Emotional Intelligence Through Artificial Intelligence: NLP and Deep Learning in the Analysis of Healthcare Texts"
date: 2023-12-01
author:
  - name: Prashant Kumar Nag
    orcid: 0000-0002-1601-1455
    affiliation: Maulana Azad National Institute of Technology, Bhopal
  - name: Amit Bhagat
    affiliation: Maulana Azad National Institute of Technology, Bhopal
  - name: R. Vishnu Priya
    affiliation: National Institute of Technology Tiruchirappalli, Tamilnadu
  - name: Deepak Kumar Khare
    affiliation: Maulana Azad National Institute of Technology, Bhopal
categories: 
  - Artificial Intelligence
  - NLP
  - Deep Learning
  - Healthcare
  - Emotion Analysis
pub-info:
  reference: >-
    <strong>Prashant Kumar Nag</strong>, Amit Bhagat, R. Vishnu Priya, and Deepak Kumar Khare, "Emotional Intelligence Through Artificial Intelligence: NLP and Deep Learning in the Analysis of Healthcare Texts," <em>2023 International Conference on Artificial Intelligence for Innovations in Healthcare Industries (ICAIIHI),</em> Raipur, India, December 2023, pp. 1-7, doi: <a href="https://doi.org/10.1109/ICAIIHI57871.2023.10489117"><code>10.1109/ICAIIHI57871.2023.10489117</code></a>
  links:
  - name: Published version
    url: https://doi.org/10.1109/ICAIIHI57871.2023.10489117
    icon: fa-solid fa-scroll
  - name: Add to Zotero
    url: https://www.zotero.org/save?type=doi&q=10.1109/ICAIIHI57871.2023.10489117
    icon: ai ai-zotero
doi: 10.1109/ICAIIHI57871.2023.10489117
---

## Abstract

This manuscript presents a methodical examination of the utilization of Artificial Intelligence (AI) in the assessment of emotions in texts related to healthcare, with a particular focus on the incorporation of Natural Language Processing (NLP) and deep learning technologies. We scrutinize numerous research studies that employ AI to augment sentiment analysis, categorize emotions, and forecast patient outcomes based on textual information derived from clinical narratives, patient feedback on medications, and online health discussions. The review demonstrates noteworthy progress in the precision of algorithms used for sentiment classification, the prognostic capabilities of AI models for neurodegenerative diseases, and the creation of AI-powered systems that offer support in clinical decision-making.

## Citation

<p class="buttons" style="text-align:center;">
<a class="btn btn-danger" target="_blank" href="https://www.zotero.org/save?type=doi&q=10.1109/ICAIIHI57871.2023.10489117">{{< ai zotero >}} Add to Zotero {{< fa square-arrow-up-right >}}</a>
</p>

```bibtex
@inproceedings{nag2023EmotionalIntelligenceArtificial,
  address = {Raipur, India},
  title = {Emotional {Intelligence} {Through} {Artificial} {Intelligence}: {NLP} and {Deep} {Learning} in the {Analysis} of {Healthcare} {Texts}},
  isbn = {979-8-3503-3091-5},
  shorttitle = {Emotional {Intelligence} {Through} {Artificial} {Intelligence}},
  url = {https://ieeexplore.ieee.org/document/10489117/},
  doi = {10.1109/ICAIIHI57871.2023.10489117},
  booktitle = {2023 {International} {Conference} on {Artificial} {Intelligence} for {Innovations} in {Healthcare} {Industries} ({ICAIIHI})},
  publisher = {IEEE},
  author = {Nag, Prashant Kumar and Bhagat, Amit and Vishnu Priya, R. and Khare, Deepak Kumar},
  month = dec,
  year = {2023},
  pages = {1--7}
}
```
